### ISSUE TITLE
Strange Error

### ISSUE THREAD

**Issue by jeremoople** [Hakanaou/deepLuna#5]
I've been doing the deepLuna translation in increments and have had minimal issues. I got up to 44% and now whenever I try to translate again, no matter the line or chunk of lines, I'm getting this.
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Jeremy\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "F:\tsukihime\deepLuna-main\deepLuna-main\deepLuna.py", line 910, in translate_game
    if self.i < cs[-1]:
IndexError: tuple index out of range
```

**Comment by Hakanaou** [comment]
Are you using the latest version of the script? It was updated several times yesterday.
Have you also try to save, close and restart the script? This can correct a certain number of strange errors.

**Comment by jeremoople** [comment]
> Are you using the latest version of the script? In particular, are you using V1 or V2 of deepLuna?
> It was updated several times in the course of the day yesterday.
> Have you also tried to save, close and restart the script? This can correct a certain number of strange errors.
I was using the older version, I didn't realize it was updated yesterday. Will I be able to resume from where I left off (44%) on the new version?
Also, I got an email that my deepL API is reaching a monthly limit for characters translated as a free account so that could be causing issues too.

**Comment by Hakanaou** [comment]
Actually, I am not one 100% sure you'll be able to start again from the same point, since the script has been deeply remodeled. It is now organized by days, so the internal database structure is actually a bit different. It might be best that you stay on the older version.
For the v1, our team actually managed to completely translated everything with deepL by big chunks of 1000 lines, so it should be working. Try maybe to delete the __pycache__ folder and restart the IDE and the script. It might also be due to the limit range of deepL, even theough there is a kind of foulproof test in the script and it shouldn't show you a python error...
If it's still not working after cleaning and restarting, and eventually after trying with another IDE, we'll try something else. Tell me how if this is the case after testing this!

**Comment by jeremoople** [comment]
> Actually, I am not one 100% sure you'll be able to start again from the same point, since the script has been deeply remodeled. It is now organized by days, so the internal database structure is actually a bit different. It might be best that you stay on the older version.
> For the v1, our team actually managed to completely translated everything with deepL by big chunks of 1000 lines, so it should be working. Try maybe to delete the **pycache** folder and restart the IDE and the script. It might also be due to the limit range of deepL, even theough there is a kind of foulproof test in the script and it shouldn't show you a python error...
> If it's still not working after cleaning and restarting, and eventually after trying with another IDE, we'll try something else. Tell me how if this is the case after testing this!

I tried those suggestions and I'm still getting the same error with both IDLE and Pyzo :/
If there doesn't end up being a solution, it's not the end of the world. I really appreciate your work on this tool and your quick responses.

**Comment by Hakanaou** [comment]
Ok, then we're going to try something else. First, can you tell me in what language are you translating with deepL?
Are you doing so linearly? If yes, I might try to debug your error if you share the table.txt file that you have in your deepLuna folder.

**Comment by jeremoople** [comment]
> Ok, then we're going to try something else. First, can you tell me in what language are you translating with deepL?
> Are you doing so linearly? If yes, I might try to debug your error if you share the table.txt file that you have in your deepLuna folder.

So... not so funny story, but shortly after you sent that, the external hard drive I had all the files on broke (physical damage, not much I could do about it.) I have a backup of the partially translated script_text.mrg, but not any of the other required files.

**Comment by Hakanaou** [comment]
Oh no, I'm so sorry to hear that! I hope you can still recover some of your most important files at least. I was ready to implement an option to import an old database in the v2 of deepLuna, but if you've lost the table.txt I guess this doesn't really help. Unfortunately, I cannot do much with the translated script_text.mrg, it is a completely reorganized file compared to the original one.
You might maybe then want to try the new version of the script when you recover everything and you have time. Anyway, I will be closing the issue at the moment, but if there is another problem just create another issue. Good luck with your recovery!
